print('something')

exit(0) # intended error